# Generated by Django 3.1.4 on 2020-12-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201206_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
