# Generated by Django 3.1.4 on 2020-12-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201206_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='destination',
            new_name='contract',
        ),
    ]
