# Generated by Django 3.1.4 on 2020-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201206_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
