# Generated by Django 3.1.4 on 2020-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201206_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
