# Generated by Django 3.1.4 on 2020-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
